networks:
  net1:



services:


  db:
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: ${USER_DB}
      POSTGRES_PASSWORD: ${PASSWORD_DB}
      POSTGRES_DB: ${NAME_DB}
    volumes:
      - .:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432
    networks:
      net1:
        aliases:
          - database

  redis:
    image: redis
    ports:
      - "6379:6379"